### ISSUE TITLE
Participate at hacktoberfest.com

### ISSUE THREAD

**Issue by xpepermint** [enquo/cretrit#4]
Details: https://hacktoberfest.com/participation/#pr-mr-details

**Comment by mpalmer** [comment]
If I'm understanding this correctly, all I need to do up-front is to tag this repo with `hacktoberfest` for the month, and then any PRs that are merged count towards your score?

**Comment by xpepermint** [comment]
Also, you should add other tags to this repo so other developers will be able to find it on GitHub search (there's currently only the description).

**Comment by mpalmer** [comment]
All Enquo repos now have the `hacktoberfest` topic (amongst others that seemed relevant).
